<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'InfanaticaCepModule\Module'                                 => __DIR__ . '/Module.php',
    'InfanaticaCepModule\Adapter\CepAdapterInterface'            => __DIR__ . '/src/InfanaticaCepModule/Adapter/CepAdapterInterface.php',
    'InfanaticaCepModule\Adapter\CorreioControlAdapter'          => __DIR__ . '/src/InfanaticaCepModule/Adapter/CorreioControlAdapter.php',
    'InfanaticaCepModule\Adapter\PostmonAdapter'                 => __DIR__ . '/src/InfanaticaCepModule/Adapter/PostmonAdapter.php',
    'InfanaticaCepModule\Adapter\RepublicaVirtualAdapter'        => __DIR__ . '/src/InfanaticaCepModule/Adapter/RepublicaVirtualAdapter.php',
    'InfanaticaCepModule\Adapter\ViaCepAdapter'                  => __DIR__ . '/src/InfanaticaCepModule/Adapter/ViaCepAdapter.php',
    'InfanaticaCepModule\Controller\CepController'               => __DIR__ . '/src/InfanaticaCepModule/Controller/CepController.php',
    'InfanaticaCepModule\Exception\CepNotFoundException'         => __DIR__ . '/src/InfanaticaCepModule/Exception/CepNotFoundException.php',
    'InfanaticaCepModule\Exception\EnderecoFormatException'      => __DIR__ . '/src/InfanaticaCepModule/Exception/EnderecoFormatException.php',
    'InfanaticaCepModule\Exception\EnderecoResponseException'    => __DIR__ . '/src/InfanaticaCepModule/Exception/EnderecoResponseException.php',
    'InfanaticaCepModule\Factory\CepControllerFactory'           => __DIR__ . '/src/InfanaticaCepModule/Factory/CepControllerFactory.php',
    'InfanaticaCepModule\Factory\CepServiceFactory'              => __DIR__ . '/src/InfanaticaCepModule/Factory/CepServiceFactory.php',
    'InfanaticaCepModule\Factory\CorreioControlAdapterFactory'   => __DIR__ . '/src/InfanaticaCepModule/Factory/CorreioControlAdapterFactory.php',
    'InfanaticaCepModule\Factory\PostmonAdapterFactory'          => __DIR__ . '/src/InfanaticaCepModule/Factory/PostmonAdapterFactory.php',
    'InfanaticaCepModule\Factory\RepublicaVirtualAdapterFactory' => __DIR__ . '/src/InfanaticaCepModule/Factory/RepublicaVirtualAdapterFactory.php',
    'InfanaticaCepModule\Factory\ViaCepAdapterFactory'           => __DIR__ . '/src/InfanaticaCepModule/Factory/ViaCepAdapterFactory.php',
    'InfanaticaCepModule\Response\EnderecoResponse'              => __DIR__ . '/src/InfanaticaCepModule/Response/EnderecoResponse.php',
    'InfanaticaCepModule\Response\EnderecoResponseInterface'     => __DIR__ . '/src/InfanaticaCepModule/Response/EnderecoResponseInterface.php',
    'InfanaticaCepModule\Service\CepService'                     => __DIR__ . '/src/InfanaticaCepModule/Service/CepService.php',
);
